### ISSUE TITLE
Admin Section To-do List

### ISSUE THREAD

**Issue by Cordelya** [Cordelya/oop#3]
- [ ] Modify db parameters for the READ/INSERT/UPDATE db access to oopglean_oop in constants.php
- [ ] Add db parameters for access to oopglean_userdata in constants.php
- [ ] Add "Edit" links to list.php, search.php and person.php. 
- [ ] Create page for editing a record. 
     * Run check against USERDATA to make sure user is authorized to make the change
     * Use loop to create a form field for each item plus copy the current data value to the value="" attribute in the input field tag.
     * list.php and search.php links should give a tabular set of fields showing all available data (ie displaying all awards for a person or group)
     * add a blank set of fields to allow a user to add a new record to awards_persons
     * Don't forget to also write the php that handles updating the db, and include an INSERT row in the transaction table
- [ ] Create page for adding new records when they don't exist: Kingdoms, Groups, Individuals, Awards
     * Don't forget to also write the php that handles inserting the new items
- [ ] Create page for adding new records in awards_persons table (award presentations)
     * Include dropdown lookup lists for items that are keyed to other tables 
     * Write the php that handles insertion
